config/routes.rb
Blog::Application.routes.draw do
    resources :posts do
        resources :comments
    end

    root  'static_pages#home'
    match '/blog',  to: 'static_pages#blog', via: 'get'
    match '/amazon_web_services_guide',  to: 'static_pages#aws_guide', via: 'get'
    match '/admin', to: 'posts#admin', via:'get'
    match '/contact', to: 'contact#index', via: 'get'

    match '*path' => redirect('/404'), via: :get
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :body, presence: true
  validates :email, presence: true
  validates :name, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    #attr_accessible :body, :title
    
    has_many :comments
    
    validates :title, :body, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        
        respond_to do |format|
	      if (comment_params[:body].present? && comment_params[:name].present? && comment_params[:email].present?)
	      	@comment = @post.comments.create!(comment_params)
	        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @post }
          UserMailer.comment_email(@comment)
          #UserMailer.comment_notification_email(@comment)
	      else
	        format.html { redirect_to @post, notice: 'Comment was missing fields, it was not created.' }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
    end

    def show
    end

    def destroy
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to blog_path }
        format.json { head :no_content }
      end
    end
    
    
    def comment_params
        params.require(:comment).permit(:body, :name, :email)
    end
    
    
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end

  def send_message
    name = params['name']
    email = params['email']
    body = params['body']
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :except => [ :index, :show ]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def admin
    redirect_to blog_path
  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :url, :image)
    end

  protected
    
    def authenticate
        authenticate_or_request_with_http_basic do |name, password|
          session[:admin] = (name == "ajm339" && password == "Iusedtoplaysoccer20")
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    
    def blog
    	@posts = Post.order("id DESC").all
    end

    def aws_guide
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<div class="row">
		<div class="large-6 columns">
	        <h6>Posted by <%= comment.name %> on <%= time_tag(comment.created_at) %></h6>
		    <p>
		        <%= comment.body %>
	        </p>
	    </div>
    </div>
    <% if session[:admin] %>
        <p>|<%= comment.id %>|</p>
        <%# link_to 'Delete', @comment, method: :delete, data: { confirm: "Are you sure you want to delete this comment? It cannot be undone." } %>
    <% end %>
<% end %>

app/views/contact/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Contact</h1>
    <h3>Ping me a message here.</h3>
    <%= form_tag()
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->

  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-4 columns">
          <p>© Alex J Meyers</p>
        </div>
        <div class="large-8 columns">
          <ul class="inline-list right">
            <li> <a href="http://www.linkedin.com/pub/alexander-meyers/84/631/581/" target="_blank">LinkedIn</a></li>
            <li> <a href="https://github.com/ajm339" target="_blank">GitHub</a></li>
            <li> <%= link_to 'Resume', 'https://s3-us-west-2.amazonaws.com/alexjmeyers/Alexander+J+Meyers+-+Resume.pdf', :target=> '_blank' %></li>
            <% if session[:admin] %>
                <li><%= link_to 'New post', new_post_path %></li>
            <% end %>
            <li><a href="#" data-reveal-id="click_modal" data-reveal>Click me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>


<div id="click_modal" class="reveal-modal" data-reveal>
  <div class="row">
    <div class="large-8 large-offset-2 columns">
      <a href="http://www.daapr.com" target='_blank'><%= image_tag('LOGO.png', alt:"daapr logo") %></a>
    </div>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/layouts/_header.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to image_tag('alexjmeyerslogosmall.png'), root_url %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li>
          <%= link_to 'Home', root_url, class:'button' %>
        </li>
        <li>
          <%= link_to 'Blog', blog_path, class:'button' %>
        </li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_navigation.html.erb
<aside class="right-off-canvas-menu" id="right_nav">
  <%= link_to 'Home', root_url, :class=>'navigation_icon' %>
  <%= link_to 'Blog', blog_path, :class=>'navigation_icon' %>
  <%= link_to 'AWS Guide', amazon_web_services_guide_path, :class=>'navigation_icon' %>
  <a href="http://www.daapr.com" class="navigation_icon" target="_blank">Daapr</a>
  <a href="http://www.myexerciseplans.com" class="navigation_icon" target="_blank">MyExercisePlans</a>
</aside>

app/views/layouts/_subnav.html.erb
<div class="row" id="subnav">
    <div id="subnav_content">
      <div class="small-10 columns">
        <%= link_to image_tag('alexjmeyers_logo.gif', id:'pageTitle'), root_url %>
      </div>
      <div class="small-2 columns">
        <a class="right-off-canvas-toggle" id="showMenu" href="#"><%= image_tag('menu.png', alt:'menu', id:'menu_icon') %></a>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Alex J Meyers, Chief Technology Officer of Daapr, Information Science major graduating May 2015 at Cornell University"> 
    
    <%= favicon_link_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "alexjmeyers" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
        <div class="inner-wrap">
            <%= render 'layouts/navigation' %>
            <section class="main-section">
                <%= render 'layouts/subnav' %>
                <%= yield %>
                <%= render 'layouts/footer' %>
            </section>
          <a class="exit-off-canvas"></a>
        </div><!--inner-wrap-->
    </div><!--off-canvas-wrap-->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, data:{abide: ''}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h6>Required = *</h6>
  <div class="field">
    <%= f.label 'Title*' %><br>
    <%= f.text_field :title, :required=> '', "required pattern" => "[a-zA-Z0-9\s]+" %>
    <small class="error">Title is required</small>
  </div>
  <div class="field">
    <%= f.label 'Body*' %><br>
    <%= f.text_area :body, :required=> '', "required pattern" => "[a-zA-Z0-9\s]+" %>
    <small class="error">Body is required</small>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="right">
    <%= f.submit class:'button'%>
  </div>

<% end %>

app/views/posts/_post.html.erb
<article>
  <meta property="og:author" content="Alex Meyers"/>
  <meta property="og:site_name" content="alexjmeyers"/>
  <meta property="og:title" content="<%= post.title %>"/>
  <% if post.image.present? %>
    <meta property="og:image" content="<%= post.image %>"/>
  <% end %>
  <meta property="og:description" content="<%= post.body %>"/>
    <h3><%= link_to_unless_current post.title, post %></h3>
    <h6>Written by Alex Meyers on <%= time_tag(post.created_at) %></h6>

    <div class="row">
      <% if post.image.present? %>
        <div class="large-7 columns">
          <p>
            <%= simple_format post.body %>
            <%# paragraph = post.body.split( "\r\n" ) %>
          </p>
        </div>
        <div class="large-5 columns">
          <%= link_to image_tag(post.image), post.url, class: 'th [radius]', :target=>'_blank' %>
        </div>
      <% else %>
        <div class="large-12 columns">
          <p>
            <%= simple_format post.body %>
            <%# paragraph = post.body.split( "\r\n" ) %>
          </p>
        </div>
      <% end %>
    </div>
</article>

app/views/posts/edit.html.erb
<% provide(:title, 'Editing ' + @post.title) %> 
<div class="row padding">
	<div class="large-8 large-offset-2 columns">
		<h3>Editing post</h3>

		<%= render 'form' %>
		<div>
			<%= link_to 'Show', @post %> |
			<%= link_to 'Back', blog_path %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<!--  <h1>Listing posts</h1> -->

 <%# render :partial => @posts %>

 <%# link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %> 
<div class="padding">
	<div class="row">
		<div class="large-8 large-offset-2 columns">
			<h4>New post</h4>

			<%= render 'form' %>

			<%= link_to 'Back', blog_path %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>  
<div class="row">
	<div class="large-12 columns">
		 <p id="notice"><%= notice %></p>
		 <div>
		 	<%= link_to 'Back', blog_path %>
		 </div>
		 <div class="padding">
		 	<%= render :partial => @post %>
		 </div>
		 <div class="padding">
           <% if session[:admin] %>
			 <%= link_to 'Edit', edit_post_path(@post) %> |
           <% end %>
			 <%= link_to 'Back', blog_path %>
           <% if session[:admin] %>
             | <%= link_to 'Delete', @post, method: :delete, data: { confirm: "Are you sure you want to delete this post? It cannot be undone." } %>
           <% end %>
		</div>
	</div>
</div>

<div class="row padding">
	<div class="large-7 columns">
		<h5>Comments</h5>
		 <div id="comments">
		         <%= render :partial => @post.comments %>
		 </div>
	</div>
	<div class="large-5 columns">
		<h5>New Comment:</h5>
		<h6>Required*</h6>
		 <%= form_for([@post, Comment.new], data:{abide: ''}) do |f| %>
		        <p>
	                <div class="field">
					    <%= f.label :name, "Name: *" %><br>
					    <%= f.text_field :name, :required=> '', "required pattern" => "[a-zA-Z]" %>
					    <small class="error">Name is required</small>
					 </div>
					 <div class="field">
					    <%= f.label :email, "Email: *" %><br>
					    <%= f.text_field :email, :required=> '', "required pattern" => "email" %>
					    <small class="error">Email is required</small>
					 </div>
					 <div class="field">
					    <%= f.label :body, "Comment: *" %><br>
					    <%= f.text_area :body, :required=> '', "required pattern" => "[a-zA-Z0-9]"%>
					    <small class="error">Body is required</small>
					 </div>
		        </p>
		        <%= f.submit "Add comment", class: "button right" %>
		<% end %>
	</div>
</div>

app/views/static_pages/aws_guide.html.erb
<% provide(:title, 'alexjmeyers aws guide') %>
<div class="row">
  <div class="large-12 columns">
    <h1>An Idiot's Guide to Amazon Web Services</h1>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <p>This page is dedicated to a guide I developed for helping new developers learn about <a href="http://aws.amazon.com/" target="_blank">Amazon Web Services</a>.</p>

    <h3>So what is Amazon Web Services, and why do you need it?</h3>

    <p>Amazon Web Services (AWS) is one of the leaders of Cloud Computing in the industry today.  It is a platform that provides various types of virtual servers that offer different solutions for hosting applications with unique services.</p>
    <p>A common theme that many people (including myself) have encountered during a college education, is that the class teaches a language and concept, but does not thoroughly demonstrate how to utilize the learning in an external application.  For example, at Cornell University, I took CS/INFO 1300 and CS/INFO 2300 and made a lot of great PHP applications. Once I completed my app, the school had set up a service for dragging and dropping our projects to the local server so that the professor could grade the project.</p>
    <p>While this is great for a simple class and helps to facilitate teaching high-level programming concepts, this created a huge issue for when I wanted to build PHP apps outside of class, because the reality is, standard servers are not neat little drag-and-drop services.</p>
    <p>If you take the time to do some research, you will find that one of the easiest solutions for deploying an application <i>in the real world</i> is a platform called <a href="http://www.heroku.com" target="_blank">Heroku</a>.  Heroku has built a fantastic service that is a robust option for apps built in well-known frameworks such as <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a>, <a href="http://nodejs.org/" target="_blank">Node.js</a>, <a href="https://www.playframework.com/" target="_blank">Play</a>, and <a href="https://www.djangoproject.com/" target="_blank">Django</a> to name a few.  Heroku is also great because it removes a lot of the complicated configuration out of Ops and lets someone boot an application by simply using Git to push to a Heroku repository.  This service is great for someone who is learning to build web applications and does not want to have to deal with the complications of DevOps; however, when it comes time to scale an application in an efficient and cost effective manner, Heroku lacks in its ability to provide deeper customization, and it is fairly expensive.</p>

    <h3>Ok, let's get to the point...</h3>

    <p>Overall, there are many intricate parts to DevOps and it is a massive undertaking.  I personally like learning new languages by following a step-by-step tutorial where I build a neat app, and the tutorial has great explanations for why it does this and not that etc (such as Michael Hartl's <a href="http://www.railstutorial.org/">Rails Tutorial</a>).  I searched far and wide, but I could not find a great tutorial for learning DevOps.  I spent 2 months of my summer vacation pulling my hair out trying to learn how to harness the power of AWS after long days at my summer internship.  My struggles (and the great documentation of Hartl's tutorial) inspired me to give back to the open source community with a tutorial of my own for learning DevOps on AWS.</p>
    <p>This tutorial would not have been possible without some of the great advice I received from <a href="http://parkermoore.de/" target="_blank">Parker Moore</a> at <a href="http://vsco.co/" target="_blank">VSCO</a> and <a href="http://www.linkedin.com/in/gregoryscallan" target="_blank">Greg Scallan</a> at <a href="https://flipboard.com/" target="_blank">Flipboard</a>.  With their help and many late nights, I finally figured out how to build a multilayer application hosted on AWS.  All of this learning put together comes in the form of the tutorial below.  This tutorial strives to explain what each piece of the puzzle is, provide additional links for more information, and then provide step-by-step how to utilize the AWS service.</p>
    <p>Notes: </p><ol><li>This tutorial is optimized for someone building a Rails Application with PostgreSQL, but its concepts can be transferred to any other framework/language.</li><li>This tutorial surrounds using Amazon's <a href="http://aws.amazon.com/opsworks/" target="_blank">OpsWorks</a> service for automation.  Opsworks is based on <a href="http://www.getchef.com/" target="_blank">Chef's</a> technology, so one could conceivably exchange out Opsworks for Chef.  <a href="http://puppetlabs.com/" target="_blank">Puppet</a> is also another automation tool that is widely used with AWS and other Cloud Computing platforms.</li><li>Find the cookbooks needed for this tutorial <a href="https://github.com/ajm339/mycookbooks" target="_blank">here</a>.</li></ol>

    <div class="show-for-medium-up">
        <iframe src='https://s3-us-west-2.amazonaws.com/alexjmeyers/AWS+Guide.pdf' style="width:718px; height:1000px;" frameborder="0"></iframe>
    </div>
    <div class="hide-for-medium-up">
        <%= link_to 'Download my Guide', 'https://s3-us-west-2.amazonaws.com/alexjmeyers/AWS+Guide.pdf', :target=> '_blank' %>
    </div>

  </div>
</div>

app/views/static_pages/blog.html.erb
<% provide(:title, 'alexjmeyers blog') %>
  <div class="row">
    <div class="large-12 columns padding">
      <h1>My Blog</h1>
    </div>
  </div>

  <div class="row">
 
    <!-- Main Blog Content -->
    <div class="large-12 columns" role="content">
 
      <%= render :partial => @posts %>

      <article class="padding">
 
        <h3><a href="#">A little about what I am doing right now</a></h3>
        <h6>Written by Alex Meyers on December 31, 2013.</h6>
 
        <div class="row">
          <div class="large-6 columns">
            <p>Right now I am in the midst of working with a great team of Cornellians to create a new social media platform called daapr.  Our goal is to build an environment which strives to make all content social.</p>
            <h5>So, what is daapr?</h5>
            <p><a href="http://www.daapr.com" target="_blank">daapr</a> is a new platform that is changing the way we share and discover online. the site allows users to curate the web with a simple, dynamically updating feed that makes sharing links amongst friends easier and more fun than ever. we’ve only just begun our journey to make content social, and we’d love your support along the way.</p>
          </div>
          <div class="large-6 columns">
            <a href="http://www.daapr.com", class= 'th [radius]', target="_blank" id="blogpic"><%= image_tag('daapr.png', alt:'daapr screenshot') %></a>
          </div>
        </div>
 
        <p class="padding">Unfortunately this website is pretty sparse at the moment.  I am currently working day and night to finalize the alpha release of daapr!  There are only two of us programming right now, myself and Connor Strynkowski, a very talented Comptuer Science major at Cornell.  We are looking forward to the addition of William Tyler Nebel to the programming team to help us speed up progress and gain some of his great insight.  Leading the business side of developing daapr is the very driven Aaron Schifrin.  Along with Aaron we have Austin Gage and Brendan Miller working tirelessly on business development for daapr.</p>

        <p>My goal is to have a very complete personal website/blog up in the next week or so.  I am preparing to build this website using the power of <a href ="http://rubyonrails.org/">Ruby on Rails</a> with the frontend framework <a href="http://foundation.zurb.com/">Foundation by Zurb</a>.  It is difficult because I am trying to balance developing daapr, this website, my family and learning so many new technologies, but I promise to have an exciting website that tells a bit about who I am along with a showcase of some of the new technologies I have leanred up within the next week or so.</p>

        <p>Thanks for stopping by!</p>
 
      </article>

      
 
    </div>
 
    <!-- End Main Content -->

app/views/static_pages/home.html.erb
  <div class="row">
    <div class="large-12 columns">
      <h1>Welcome to my personal website!<h1>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns padding">
      <div class="show-for-medium-up">
        <ul class="orbit" data-orbit>
          <li>
            <%= image_tag 'daapr_team.jpg' %>
            <div class="orbit-caption">
              The Daapr Team
            </div>
          </li>
          <li>
            <div class="center">
              <h2>Check out my Amazon Web Services <%= link_to 'Guide', amazon_web_services_guide_path%>.</h2>
            </div>
          </li>
          <li>
            <%= image_tag 'zipline.jpg' %>
            <div class="orbit-caption">
              Just a little bit about myself...
            </div>
          </li>
          <li>
            <%= image_tag 'alaska.jpg' %>
            <div class="orbit-caption">
              My family and I travel to cool places like Alaska...
            </div>
          </li>
          <li>
            <%= image_tag 'hawaii2.jpg' %>
            <div class="orbit-caption">
              ...and Mauna Kea in Hawaii as well.
            </div>
          </li>
          <li>
            <div class="center">
              <h2>Thanks for visiting my website!</h2>
              <h2>Check out my <%= link_to 'blog', blog_path %> too.</h2>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row padding">
    <div class="large-12 columns">
      <h6 class="centertext">
        Hey there.  My name is Alex Meyers and this is my personal website.
      </h6>
      <h6 class="centertext">
        I am an Information Science Major at Cornell University graduating May 2015.
      </h6>
      <h6 class="centertext">
        I am currently working on a cool new startup called <a href='http://www.daapr.com' target="_blank">daapr</a>.
      </h6>
      <h6 class="centertext">
        Check out my <a href='https://alex-twitter.herokuapp.com' target="_blank">sample twitter application</a> that I made with Rails.
      </h6>
      <h6 class="centertext">
        Feel free to email me at ajm339@cornell.edu
      <h6>
    </div>
  </div>